export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');
export const CREATE_TRANSACTION_USE_CASE = Symbol('CREATE_TRANSACTION_USE_CASE');
export const GET_TRANSACTION_USE_CASE = Symbol('GET_TRANSACTION_USE_CASE');
